[package]
name = "ws"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"

[dependencies]
async-std = "1.12.0"
futures = "0.3.28"
httparse = "1.8.0"
tokio = { version = "1.32.0", features = ["full"] }
